# Generated by Django 2.1.7 on 2019-03-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0003_remove_task_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Task', to='codev_app.Task'),
        ),
    ]
