# Generated by Django 2.1.7 on 2019-03-20 21:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0009_auto_20190318_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='902c61f922d44cb78b257f5ef2097c81', max_length=30)),
                ('creation_date', models.CharField(default=datetime.time(21, 23, 39, 907124), max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 21, 23, 39, 905422)),
        ),
    ]
