# Generated by Django 2.1.7 on 2019-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0009_auto_20190308_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='users'),
        ),
    ]
