# Generated by Django 2.1.7 on 2019-03-14 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0011_auto_20190310_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 21, 1, 24, 51831)),
        ),
    ]
