# Generated by Django 2.1.7 on 2019-03-21 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0011_auto_20190320_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='simple_about',
            field=models.TextField(default='Краткое описание', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='body',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 21, 20, 24, 16, 878970)),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(default=datetime.time(20, 24, 16, 882285), max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='a01502347ed944cbbb97bd1b2f4dd28a', max_length=30),
        ),
    ]
