# Generated by Django 2.1.7 on 2019-03-17 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0013_auto_20190317_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 17, 17, 57, 6, 363499)),
        ),
    ]
