# Generated by Django 2.2 on 2019-04-09 20:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0040_auto_20190409_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 20, 5, 25, 133430)),
        ),
        migrations.RemoveField(
            model_name='task',
            name='subs',
        ),
        migrations.AddField(
            model_name='task',
            name='subs',
            field=models.ManyToManyField(to='codev_app.Subscribe'),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(default=datetime.time(20, 5, 25, 138038), max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='241f8879ff2f423b8f305575fb8e49c8', max_length=30),
        ),
    ]
