# Generated by Django 2.2 on 2019-04-09 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0047_auto_20190409_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 20, 11, 59, 347883)),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(default=datetime.time(20, 11, 59, 349605), max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='47e48e6fe3244ff98a55e361e9b1bdbc', max_length=30),
        ),
    ]
