# Generated by Django 2.2 on 2019-04-10 19:19

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0052_auto_20190409_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='time_joined',
            new_name='time_subscribed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subs',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='task',
            field=models.ManyToManyField(default=None, related_name='subscribtion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='user',
            field=models.ManyToManyField(default=None, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 19, 18, 57, 789485)),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(default=datetime.time(19, 18, 57, 792506), max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='054ee6f074434634a1160dd4469cd8ed', max_length=30),
        ),
    ]
