# Generated by Django 2.2 on 2019-04-10 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0054_auto_20190410_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='task',
            field=models.ManyToManyField(default=None, related_name='subscribtion', to='codev_app.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 19, 35, 4, 278678)),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(default=datetime.time(19, 35, 4, 281848), max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='f68ab1e3ec1a4da4a314bd2d1895505b', max_length=30),
        ),
    ]
