# Generated by Django 2.2 on 2019-04-10 19:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0056_auto_20190410_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='task',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='task',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='codev_app.Task'),
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 10, 19, 41, 29, 546650)),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(default=datetime.time(19, 41, 29, 548199), max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='8722f51673654594a6b2ba2a37593ce6', max_length=30),
        ),
    ]
