# Generated by Django 2.1.7 on 2019-04-14 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codev_app', '0070_auto_20190414_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 14, 16, 27, 24, 362883)),
        ),
        migrations.AlterField(
            model_name='token',
            name='creation_date',
            field=models.CharField(default=datetime.time(16, 27, 24, 364101), max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default='b70eb1d96142452db7bb662adaad9c11', max_length=30),
        ),
    ]
